---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.8.1

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver:
      box: chef/windows-server-2016-standard
      customize:
        cpus: 2
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[scottford_windows_hardening::default]
    verifier:
      inspec_tests:
        - name: scottford_windows_baseline
          path: /Users/scottford/src/quick_dca_workshop/scottford_windows_baseline
    attributes:
